version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: moview-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: moview
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  eureka-server:
    build: 
      context: ./eureka-server
      dockerfile: Dockerfile
    container_name: moview-eureka
    ports:
      - "8762:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mysql:
        condition: service_healthy

  config-server:
    build: 
      context: ./config-server
      dockerfile: Dockerfile
    container_name: moview-config
    ports:
      - "8889:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      eureka-server:
        condition: service_started

  api-gateway:
    build: 
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: moview-gateway
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      config-server:
        condition: service_started
      eureka-server:
        condition: service_started

  bootloader:
    build: 
      context: ./bootloader
      dockerfile: Dockerfile
    container_name: moview-bootloader
    ports:
      - "8083:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/moview
    depends_on:
      mysql:
        condition: service_healthy
      api-gateway:
        condition: service_started

volumes:
  mysql-data:

networks:
  default:
    driver: bridge